### ISSUE TITLE
Problem loading feedrUI with R4.2.3 and Rstudio 2023.03.0

### ISSUE THREAD

**Issue by ehofmeister** [steffilazerte/feedr#8]
Error message:
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘feedrUI’ is not available for this version of R

**Comment by steffilazerte** [comment]
Hi @ehofmeister, neither `feedr` nor the `feedrUI` are available from CRAN.
If you want to install the `feedrUI` package you'll need to install from GitHub using the 'remotes' package:

```
install.packages('remotes')
remotes::install_github("animalnexus/feedrUI")
```
I haven't worked on feedrUI in a while so let me know if you run into any problems.

**Comment by ehofmeister** [comment]
Hi Steffi, I tried that and here is the R response:
> install.packages('remotes')
Installing package into ‘C:/Users/ehofmeister/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mirror.las.iastate.edu/CRAN/src/contrib:
  cannot open URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.2:
  cannot open URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.2/PACKAGES'
Warning message:
package ‘remotes’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> remotes::install_github("animalnexus/feedrUI")
e
________________________________
From: Steffi LaZerte ***@***.***>
Sent: Wednesday, March 22, 2023 4:19 PM
To: animalnexus/feedr ***@***.***>
Cc: Hofmeister, Erik K ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [animalnexus/feedr] Problem loading feedrUI with R4.2.3 and Rstudio 2023.03.0 (Issue #8)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @ehofmeister<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fehofmeister&data=05%7C01%7Cehofmeister%40usgs.gov%7C516856285d154fa44b9908db2b1b2f48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638151167982069374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bmk92D5VpgYe3oSjTkumz7fyv7aCA2wkfPRT0vaTVhs%3D&reserved=0>, neither feedr nor the feedrUI are available from CRAN.
If you want to install the feedrUI package you'll need to install from GitHub using the 'remotes' package:

install.packages('remotes')
remotes::install_github("animalnexus/feedrUI")


I haven't worked on feedrUI in a while so let me know if you run into any problems.

**Comment by steffilazerte** [comment]
Hmm, looks like you might have bigger problems 😅.
Have you had success installing other packages? Looks like this is related to your specific settings. It looks like you're trying to use a local mirror (mirror.las.iastat.edu) rather than a more generic one.

I'm not 100% how to fix this, but if you're using RStudio, try going to Tools > Global Options > Packages and changing the "Primary CRAN repository" to something else. 

Then try installing remotes again, and hopefully it'll work!

**Comment by ehofmeister** [comment]
Hi again, I am not skilled at the nuances of loading packages. I have more experience using ggplot2 to make figures.
But... in Rstudio I successfully loaded remotes but then it wouldn't load feedrUL

In R GUI (I think the non Rstudio interface is called , I could load remotes but it also wouldn't load feedrUL:
package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\ehofmeister\AppData\Local\Temp\1\RtmpMvPKSd\downloaded_packages
> remotes::install_github("animalnexus/feedrUI")
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/animalnexus/feedrUI/contents/DESCRIPTION?ref=HEAD'

It seems I am blocked from opening api.github.com.

I am using reader cards from EIk Bridge and really need your program to extract the data.

thanks e
________________________________
From: Steffi LaZerte ***@***.***>
Sent: Wednesday, March 22, 2023 4:19 PM
To: animalnexus/feedr ***@***.***>
Cc: Hofmeister, Erik K ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [animalnexus/feedr] Problem loading feedrUI with R4.2.3 and Rstudio 2023.03.0 (Issue #8)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @ehofmeister<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fehofmeister&data=05%7C01%7Cehofmeister%40usgs.gov%7C516856285d154fa44b9908db2b1b2f48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638151167982069374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bmk92D5VpgYe3oSjTkumz7fyv7aCA2wkfPRT0vaTVhs%3D&reserved=0>, neither feedr nor the feedrUI are available from CRAN.
If you want to install the feedrUI package you'll need to install from GitHub using the 'remotes' package:

install.packages('remotes')
remotes::install_github("animalnexus/feedrUI")


I haven't worked on feedrUI in a while so let me know if you run into any problems.

**Comment by steffilazerte** [comment]
Hmm, okay, well another way to install it would be from my R-Universe:

```
install.packages('feedrUI', repos = c('https://steffilazerte.r-universe.dev', 'https://cloud.r-project.org'))
```

Also, if you're familiar with coding in R, you might find the `feedr` package more robust. The `feedrUI` package gives a GUI interface but I haven't worked on it in years so I'm not sure how it's doing. The `feedr` package does all the same things but via R coding (`feedrUI` uses `feedr`).

`feedr` can be installed the same way, just using `feedr` instead of `feedrUI`. 

Good luck!

**Comment by ehofmeister** [comment]
Hi, I think I have it! On a whim I tried to download it on the lab computer and I think it's all there. RGui 4.0.2!
Will try to work with it tomorrow. If I have questions should I just use this email?
I'm interested in seeing how it processes birds that stay at the antenna for a prolonged time. I have it set to not record the same bird unless they are present for >= 5 sec. I'm using this with caged zebra finches and tox studies.

thanks Erik
________________________________
From: Steffi LaZerte ***@***.***>
Sent: Thursday, March 23, 2023 1:21 PM
To: animalnexus/feedr ***@***.***>
Cc: Hofmeister, Erik K ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [animalnexus/feedr] Problem loading feedrUI with R4.2.3 and Rstudio 2023.03.0 (Issue #8)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hmm, okay, well another way to install it would be from my R-Universe:

install.packages('feedrUI', repos = c('https://steffilazerte.r-universe.dev', 'https://cloud.r-project.org'))


Also, if you're familiar with coding in R, you might find the feedr package more robust. The feedrUI package gives a GUI interface but I haven't worked on it in years so I'm not sure how it's doing. The feedr package does all the same things but via R coding (feedrUI uses feedr).

feedr can be installed the same way, just using feedr instead of feedrUI.

Good luck!

**Comment by steffilazerte** [comment]
Great! You'll probably want to adjust the `bw` (between) measurement for visits, etc. Have you seen the tutorial document (https://animalnexus.github.io/feedr/)? That should help you get started (although it is a bit out of date in places I'm afraid). 

For generic questions, use my email sel@steffilazerte.ca. For specific bugs you run into, posting it here on the GitHub issues isn't a bad idea (it's a public area, so others who have the same problem can see the discussion surrounding it).
